# ablation study
# # GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8, 16] use_layer_learning=False
# CUDA_VISIBLE_DEVICES=0 nohup python o3_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=False instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_no_layer.out 2>&1 &

# # GS4LS iwls2epfl normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8, 16] use_layer_learning=False
# CUDA_VISIBLE_DEVICES=7 nohup python o3_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=False instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_no_layer.out 2>&1 &

# # GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8, 16] use_layer_learning=True logits_parentsib=False
# CUDA_VISIBLE_DEVICES=0 nohup python o3_train_gs4co.py --config_name train_gs4co dso_agent_kwargs.transformer_kwargs.logits_parentsib=False train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_no_logits_parentsib.out 2>&1 &

# # GS4LS iwls2epfl normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8, 16] use_layer_learning=True logits_parentsib=False
# CUDA_VISIBLE_DEVICES=1 nohup python o3_train_gs4co.py --config_name train_gs4co dso_agent_kwargs.transformer_kwargs.logits_parentsib=False train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_no_logits_parentsib.out 2>&1 &

# # GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8, 16] use_layer_learning=True train_algo="GRPO"
# CUDA_VISIBLE_DEVICES=2 nohup python o3_train_gs4co.py --config_name train_gs4co rl_algo_kwargs.kwargs.train_algo="GRPO" train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_GPRO.out 2>&1 &

# # GS4LS iwls2epfl normalize entropy_coef=0.2 featur=no_lut normalize_pred_y BON=[1, 2, 4, 8, 16] use_layer_learning=True train_algo="GRPO"
# CUDA_VISIBLE_DEVICES=3 nohup python o3_train_gs4co.py --config_name train_gs4co rl_algo_kwargs.kwargs.train_algo="GRPO" train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_GPRO.out 2>&1 &

# GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8, 16] use_layer_learning=True structural_encoding=False
CUDA_VISIBLE_DEVICES=5 nohup python o3_train_gs4co.py --config_name train_gs4co dso_agent_kwargs.transformer_kwargs.structural_encoding=False train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_no_structural_encoding.out 2>&1 &

# GS4LS iwls2epfl normalize entropy_coef=0.2 featurlut normalize_pred_y BON=[1, 2, 4, 8, 16] use_layer_learning=True structural_encoding=False
CUDA_VISIBLE_DEVICES=6 nohup python o3_train_gs4co.py --config_name train_gs4co dso_agent_kwargs.transformer_kwargs.structural_encoding=False train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_no_structural_encoding.out 2>&1 &