# # GS4LS hyp unnormalize
# CUDA_VISIBLE_DEVICES=1 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=Hyp train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/train train_data_loader.kwargs.normalize=False test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/test test_data_loader.kwargs.normalize=False > ./out/GS4LS_Hyp_mse_score_unnormalize.out 2>&1 &
# sleep 10s
# # GS4LS hyp normalize
# CUDA_VISIBLE_DEVICES=2 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=Hyp train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/train train_data_loader.kwargs.normalize=True test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/test test_data_loader.kwargs.normalize=True > ./out/GS4LS_Hyp_mse_score_normalize.out 2>&1 &
# sleep 10s
# GS4LS hyp normalize entropy_coef=0.02
# CUDA_VISIBLE_DEVICES=1 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=Hyp rl_algo_kwargs.kwargs.entropy_coef=0.02 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/train train_data_loader.kwargs.normalize=True test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/test test_data_loader.kwargs.normalize=True > ./out/GS4LS_Hyp_mse_score_normalize_entropy_coef_0.02.out 2>&1 &
# sleep 10s
# GS4LS hyp normalize entropy_coef=0.02 feature=no_lut
# CUDA_VISIBLE_DEVICES=2 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=Hyp rl_algo_kwargs.kwargs.entropy_coef=0.02 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/GS4LS_Hyp_mse_score_normalize_entropy_coef_0.02_no_lut.out 2>&1 &
# wait

# GS4LS hyp normalize entropy_coef=0.02 feature=no_lut unnormalize_pred_y
# CUDA_VISIBLE_DEVICES=1 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=Hyp rl_algo_kwargs.kwargs.entropy_coef=0.02 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/GS4LS_Hyp_mse_score_normalize_entropy_coef_0.02_no_lut_unnormalize_pred_y.out 2>&1 &

# GS4LS hyp normalize entropy_coef=0.02 feature=no_lut normalize_pred_y
# CUDA_VISIBLE_DEVICES=0 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=Hyp rl_algo_kwargs.kwargs.entropy_coef=0.02 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/GS4LS_Hyp_mse_score_normalize_entropy_coef_0.02_no_lut_normalize_pred_y.out 2>&1 &

# # GS4LS hyp normalize entropy_coef=0.2 feature=no_lut unnormalize_pred_y
# CUDA_VISIBLE_DEVICES=0 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=Hyp rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/GS4LS_Hyp_mse_score_normalize_entropy_coef_0.2_no_lut_unnormalize_pred_y.out 2>&1 &

# # GS4LS hyp normalize entropy_coef=0.2 feature=no_lut unnormalize_pred_y BON=16
# CUDA_VISIBLE_DEVICES=1 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=Hyp instance_kwargs.Best_of_N=16 rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/GS4LS_Hyp_mse_score_normalize_entropy_coef_0.2_no_lut_unnormalize_pred_y_BON_16.out 2>&1 &

# GS4LS Square normalize entropy_coef=0.2 feature=no_lut unnormalize_pred_y BON=16
CUDA_VISIBLE_DEVICES=2 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=Square instance_kwargs.Best_of_N=16 rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Square/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Square/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/GS4LS_Square_mse_score_normalize_entropy_coef_0.2_no_lut_unnormalize_pred_y_BON_16.out 2>&1 &

# GS4LS Multiplier normalize entropy_coef=0.2 feature=no_lut unnormalize_pred_y BON=16
CUDA_VISIBLE_DEVICES=3 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=Multiplier instance_kwargs.Best_of_N=16 rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Multiplier/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Multiplier/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/GS4LS_Multiplier_mse_score_normalize_entropy_coef_0.2_no_lut_unnormalize_pred_y_BON_16.out 2>&1 &

# GS4LS Conmax normalize entropy_coef=0.2 feature=no_lut unnormalize_pred_y BON=16
CUDA_VISIBLE_DEVICES=4 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=Conmax instance_kwargs.Best_of_N=16 rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Conmax/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Conmax/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/GS4LS_Conmax_mse_score_normalize_entropy_coef_0.2_no_lut_unnormalize_pred_y_BON_16.out 2>&1 &

# GS4LS Desperf normalize entropy_coef=0.2 feature=no_lut unnormalize_pred_y BON=16
CUDA_VISIBLE_DEVICES=5 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=Desperf instance_kwargs.Best_of_N=16 rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Desperf/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Desperf/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/GS4LS_Desperf_mse_score_normalize_entropy_coef_0.2_no_lut_unnormalize_pred_y_BON_16.out 2>&1 &

# GS4LS Ethernet normalize entropy_coef=0.2 feature=no_lut unnormalize_pred_y BON=16
CUDA_VISIBLE_DEVICES=6 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=Ethernet instance_kwargs.Best_of_N=16 rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Ethernet/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Ethernet/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/GS4LS_Ethernet_mse_score_normalize_entropy_coef_0.2_no_lut_unnormalize_pred_y_BON_16.out 2>&1 &

# GS4LS iwls2epfl normalize entropy_coef=0.2 feature=no_lut unnormalize_pred_y BON=16
CUDA_VISIBLE_DEVICES=7 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=iwls2epfl instance_kwargs.Best_of_N=16 rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/GS4LS_iwls2epfl_mse_score_normalize_entropy_coef_0.2_no_lut_unnormalize_pred_y_BON_16.out 2>&1 &

# GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut unnormalize_pred_y BON=16
CUDA_VISIBLE_DEVICES=0 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse instance_kwargs.instance_type=epfl2iwls instance_kwargs.Best_of_N=16 rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/GS4LS_epfl2iwls_mse_score_normalize_entropy_coef_0.2_no_lut_unnormalize_pred_y_BON_16.out 2>&1 &

# GS4LS Hyp normalize entropy_coef=0.2 feature=no_lut unnormalize_pred_y BON=[3, 6, 9] use_layer_learning=True
CUDA_VISIBLE_DEVICES=3 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse train_kwargs.use_layer_learning=True instance_kwargs.instance_type=Hyp 'instance_kwargs.Best_of_N=[3, 6, 9]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/Hyp_mse_score_normalize_entropy_coef_0.2_no_lut_unnormalize_pred_y_BON_369_layer.out 2>&1 &

# GS4LS Hyp normalize entropy_coef=0.2 feature=no_lut unnormalize_pred_y BON=[3, 6, 9] use_layer_learning=False
CUDA_VISIBLE_DEVICES=4 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse train_kwargs.use_layer_learning=False instance_kwargs.instance_type=Hyp 'instance_kwargs.Best_of_N=[3, 6, 9]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/Hyp_mse_score_normalize_entropy_coef_0.2_no_lut_unnormalize_pred_y_BON_369_no_layer.out 2>&1 &

# GS4LS Hyp normalize entropy_coef=0.2 feature=no_lut unnormalize_pred_y BON=[4， 8， 16] use_layer_learning=True
CUDA_VISIBLE_DEVICES=3 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=mse train_kwargs.use_layer_learning=True instance_kwargs.instance_type=Hyp 'instance_kwargs.Best_of_N=[4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.02 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/Hyp_mse_score_normalize_entropy_coef_0.02_no_lut_normalize_pred_y_BON_4816_layer.out 2>&1 &

# GS4LS Hyp normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[4, 8, 16] use_layer_learning=True
CUDA_VISIBLE_DEVICES=4 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True instance_kwargs.instance_type=Hyp 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Hyp/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/Hyp_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_layer.out 2>&1 &

# GS4LS Conmax normalize entropy_ceof=0.2 feature=no_lut normalize_pred_y BON=[4, 8, 16] use_layer_learning=True
CUDA_VISIBLE_DEVICES=1 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True instance_kwargs.instance_type=Conmax 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Conmax/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Conmax/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/Conmax_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_layer.out 2>&1 &

# GS4LS Desperf normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[4, 8, 16] use_layer_learning=True
CUDA_VISIBLE_DEVICES=2 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True instance_kwargs.instance_type=Desperf 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Desperf/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Desperf/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/Desperf_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_layer.out 2>&1 &

# GS4LS Ethernet normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[4, 8, 16] use_layer_learning=True
CUDA_VISIBLE_DEVICES=3 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True instance_kwargs.instance_type=Ethernet 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Ethernet/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Ethernet/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/Ethernet_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_layer.out 2>&1 &

# GS4LS Multiplier normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8, 16] use_layer_learning=True
CUDA_VISIBLE_DEVICES=5 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True instance_kwargs.instance_type=Multiplier 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Multiplier/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Multiplier/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/Multiplier_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_layer.out 2>&1 &

# GS4LS Square normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8, 16] use_layer_learning=True
CUDA_VISIBLE_DEVICES=6 nohup python 03_train_gs4co.py --config_name train_gs4co train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True instance_kwargs.instance_type=Square 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Square/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/in-domain-test/Square/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/Square_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_layer.out 2>&1 &

# GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8, 16] use_layer_learning=True seed=1
CUDA_VISIBLE_DEVICES=6 nohup python o3_train_gs4co.py --config_name train_gs4co train_kwargs.seed=1 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_layer_seed1.out 2>&1 &

# GS4LS iwls2epfl normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8, 16] use_layer_learning=True seed=1
CUDA_VISIBLE_DEVICES=7 nohup python o3_train_gs4co.py --config_name train_gs4co train_kwargs.seed=1 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8, 16]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_124816_layer_seed1.out 2>&1 &

# GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=False seed=0 layer=3
CUDA_VISIBLE_DEVICES=2 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=False train_kwargs.use_multi_layer=True 'train_kwargs.num_messages=[5, 5, 5]' instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_layer3.out 2>&1 &

# GS4LS iwls2epfl normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=False seed=0 layer=3
CUDA_VISIBLE_DEVICES=3 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=False train_kwargs.use_multi_layer=True 'train_kwargs.num_messages=[5, 5, 5]' instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_layer3.out 2>&1 &

# GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=False seed=0 layer=1
CUDA_VISIBLE_DEVICES=0 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=False train_kwargs.use_multi_layer=True 'train_kwargs.num_messages=[5]' instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_layer1.out 2>&1 &

# GS4LS iwls2epfl normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=False seed=0 layer=1
CUDA_VISIBLE_DEVICES=1 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=False train_kwargs.use_multi_layer=True 'train_kwargs.num_messages=[5]' instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_layer1.out 2>&1 &

# GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True transformer_num_layers=6
CUDA_VISIBLE_DEVICES=4 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True dso_agent_kwargs.transformer_kwargs.num_layers=6 instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_transformer6.out 2>&1 &

# GS4LS iwls2epfl normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True transformer_num_layers=6
CUDA_VISIBLE_DEVICES=5 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True dso_agent_kwargs.transformer_kwargs.num_layers=6 instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_transformer6.out 2>&1 &

# GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True transformer_num_layers=8
CUDA_VISIBLE_DEVICES=4 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True dso_agent_kwargs.transformer_kwargs.num_layers=8 instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_transformer8.out 2>&1 &

# GS4LS iwls2epfl normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True transformer_num_layers=8
CUDA_VISIBLE_DEVICES=5 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True dso_agent_kwargs.transformer_kwargs.num_layers=8 instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_transformer8.out 2>&1 &

# GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True train_data=100
CUDA_VISIBLE_DEVICES=6 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True  instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.max_samples=100 train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_traindata100.out 2>&1 &

# GS4LS iwls2epfl normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True train_data=100
CUDA_VISIBLE_DEVICES=7 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True  instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.max_samples=100 train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_traindata100.out 2>&1 &

# GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True train_data=1000
CUDA_VISIBLE_DEVICES=6 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True  instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.max_samples=1000 train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_traindata1000.out 2>&1 &

# GS4LS iwls2epfl normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True train_data=1000
CUDA_VISIBLE_DEVICES=7 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True  instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.max_samples=1000 train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_traindata1000.out 2>&1 &

# GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True train_data=10000
CUDA_VISIBLE_DEVICES=6 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True  instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.max_samples=10000 train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_traindata10000.out 2>&1 &

# GS4LS iwls2epfl normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True train_data=10000
CUDA_VISIBLE_DEVICES=7 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True  instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.max_samples=10000 train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_traindata10000.out 2>&1 &

# GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True math_list=all
CUDA_VISIBLE_DEVICES=0 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True  instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' expression_kwargs.math_list=all rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True  train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_math_all.out 2>&1 &

# GS4LS iwls2epfl normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True math_list=all
CUDA_VISIBLE_DEVICES=1 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True  instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' expression_kwargs.math_list=all rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True  train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_math_all.out 2>&1 &

# GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True special_encoding=True
CUDA_VISIBLE_DEVICES=1 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True  instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' dso_agent_kwargs.transformer_kwargs.special_encoding=True rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True  train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_special_encoding.out 2>&1 &

# GS4LS iwls2epfl normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True special_encoding=True
CUDA_VISIBLE_DEVICES=1 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True  instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' dso_agent_kwargs.transformer_kwargs.special_encoding=True rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True  train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_special_encoding.out 2>&1 &

# GS4LS epfl2iwls normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True layer_min_length=[16, 12, 8]
CUDA_VISIBLE_DEVICES=6 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True  instance_kwargs.instance_type=epfl2iwls 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' 'dso_agent_kwargs.transformer_kwargs.layer_min_length=[16, 12, 8]' 'dso_agent_kwargs.transformer_kwargs.layer_max_length=[100, 50, 20]' 'dso_agent_kwargs.transformer_kwargs.layer_soft_length=[58, 31, 14]' dso_agent_kwargs.transformer_kwargs.logits_parentsib=True rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/epfl2iwls/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/epfl2iwls_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_longer_length.out 2>&1 &

# GS4LS iwls2epfl normalize entropy_coef=0.2 feature=no_lut normalize_pred_y BON=[1, 2, 4, 8] use_layer_learning=True layer_min_length=[16, 12, 8]
CUDA_VISIBLE_DEVICES=7 nohup python o3_train_gs4co.py --config-name train_gs4co train_kwargs.seed=0 train_kwargs.score_func_name=focal_loss train_kwargs.use_layer_learning=True  instance_kwargs.instance_type=iwls2epfl 'instance_kwargs.Best_of_N=[1, 2, 4, 8]' 'dso_agent_kwargs.transformer_kwargs.layer_min_length=[16, 12, 8]' 'dso_agent_kwargs.transformer_kwargs.layer_max_length=[100, 50, 20]' 'dso_agent_kwargs.transformer_kwargs.layer_soft_length=[58, 31, 14]' dso_agent_kwargs.transformer_kwargs.logits_parentsib=True rl_algo_kwargs.kwargs.entropy_coef=0.2 train_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/train train_data_loader.kwargs.normalize=True train_data_loader.kwargs.feature_selection=no_lut test_data_loader.kwargs.npy_data_path=./dataset/out-of-domain-test/iwls2epfl/test test_data_loader.kwargs.normalize=True test_data_loader.kwargs.feature_selection=no_lut > ./out/iwls2epfl_focal_loss_score_normalize_entropy_coef_0.2_no_lut_normalize_pred_y_BON_1248_layer_longer_length.out 2>&1 &

python 04_test_gs4co.py --config_name train_gs4co test_data_loader.kwargs.npy_data_path=/home/yqbai/ldpan/GS4LS/gs4-ls-updated/dataset/in-domain-test/Hyp/test test_kwargs.model_path=/home/yqbai/ldpan/GS4LS/gs4-ls-updated/results/results/train_graph/Hyp/default/0827105657_cb1a02e/0_0/state_dict/hyp/BON_16/train_iter_2000.pkl